-- 코드를 입력하세요
SELECT ID, NAME, PLACES.HOST_ID FROM PLACES INNER JOIN 
(SELECT COUNT(HOST_ID) AS HEAVY_USER, HOST_ID FROM PLACES GROUP BY HOST_ID) AS A 
ON PLACES.HOST_ID = A.HOST_ID
WHERE A.HEAVY_USER>=2
ORDER BY ID;